version: '3'

networks:
  proxy: 
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - 3000:80
    networks:
      - proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  app1:
    image: mlinha:latest
    container_name: mlinha-1
    volumes:
      - ./app:/app
    networks:
      - proxy